classdef (Abstract) Preparation < symphonyui.core.persistent.descriptions.SourceDescription
    
    methods
        
        function obj = Preparation()
            import symphonyui.core.*;
            
            obj.addProperty('time', datestr(now), ...
                'type', PropertyType('char', 'row', 'datestr'), ...
                'description', 'Time the preparation was prepared');
            obj.addProperty('dissector', 'Angueyra', ...
                'type', PropertyType('char', 'row', {'', 'Angueyra', 'Chen', 'Kunze', 'Zhao', 'Ball', 'Li', 'Ou', 'Qiao'}), ...
                'description', 'Time the preparation was prepared');
            obj.addProperty('tissue', '', ...
                'type', PropertyType('char', 'row', containers.Map( ...
                    {'retina', 'pineal gland', 'other'}, ...
                    {{}, ...
                    {'', 'whole mount cones', 'whole mount RGCs ', 'slice', 'chopped retina', 'shredded retina', 'dissociated cells'}, ...
                    {'whole mount', 'slice', 'dissociated cells'}, ...
                    {'whole mount', 'slice', 'dissociated cells'}})), ...
					);
			%obj.addProperty('preparation', '', ...
            %    'type', PropertyType('char', 'row', ));
            obj.addProperty('bathSolution', '', ...
                'type', PropertyType('char', 'row', {'', 'AmesBicarb', 'AmesHEPES', 'HibA'}), ...
                'description', 'The solution the preparation is bathed in during experiments');   
            obj.addProperty('storageSolution', '', ...
                'type', PropertyType('char', 'row', {'', 'AmesBicarb', 'AmesHEPES', 'HibA'}), ...
                'description', 'The solution the preparation is stored in');
            obj.addProperty('storageTemp', '', ...
                'type', PropertyType('int32', 'row', {'', 4, 22, 37}), ...
                'description', 'The temperature of the solution the preparation is stored in');   
        end
        
    end
    
end

