classdef (Abstract) Preparation < symphonyui.core.persistent.descriptions.SourceDescription
    
    methods
        
        function obj = Preparation()
            import symphonyui.core.*;
            
            obj.addProperty('time', datestr(now), ...
                'type', PropertyType('char', 'row', 'datestr'), ...
                'description', 'Time the preparation was prepared');
            obj.addProperty('dissector', 'Angueyra', ...
                'type', PropertyType('char', 'row', {'', 'Angueyra', 'Chen', 'Kunze', 'Zhao', 'Ball', 'Li', 'Ou', 'Qiao'}), ...
                'description', 'Time the preparation was prepared');
            obj.addProperty('tissue', 'retina', ...
                'type', PropertyType('char', 'row', {'retina', 'pineal gland', 'other'}));
			obj.addProperty('preparation', {}, ...
                'type', PropertyType('cellstr', 'row', {'whole mount cones', 'whole mount RGCs', 'slice'}));
            obj.addProperty('bathSolution', '', ...
                'type', PropertyType('char', 'row', {'', 'AmesBicarb', 'AmesHEPES', 'HibA'}), ...
                'description', 'The solution the preparation is bathed in during experiments');   
            obj.addProperty('storageSolution', '', ...
                'type', PropertyType('char', 'row', {'', 'AmesBicarb', 'AmesHEPES', 'HibA'}), ...
                'description', 'The solution the preparation is stored in');
            obj.addProperty('storageTemp', '', ...
                'type', PropertyType('char', 'row', {'', 'fridge', 'room temp', 'warm'}), ...
                'description', 'The temperature of the solution the preparation is stored in');   
        end
        
    end
    
end

