classdef SqRetPrep < squirrellab.sources.Preparation
    
    methods
        
        function obj = SqRetPrep()
            import symphonyui.core.*;
            
			obj.addProperty('region', {}, ...
    			'type', PropertyType('cellstr', 'row', {'superior', 'inferior', 'nasal', 'temporal'}));
			obj.addProperty('eye', '', ...
    			'type', PropertyType('char', 'row', {'','left', 'right'}));
			obj.addProperty('viral transfection', '', ...
    			'type', PropertyType('char', 'row', {'', 'subretinal', 'intravitreal'}));
			obj.addProperty('viral transfection date', '', ...
                'type', PropertyType('char', 'row', 'datestr'), ...
                'description', 'Date virus was injected');
            obj.addProperty('viral serotype', '', ...
				'type', PropertyType('char', 'row', {...
                '',...
                'AAV1',...
                'AAV2',...
                'AAV2o1SyniGluSnfr'}));
			
            obj.addAllowableParentType('squirrellab.sources.squirrel.Squirrel');
        end
        
    end
    
end

